packages:
  - model
  - ui
  - workflow
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.52.3
  "@platforma-sdk/ui-vue": ^1.52.3
  "@platforma-sdk/workflow-tengo": ^5.8.0
  "@platforma-sdk/block-tools": ^2.6.31
  "@platforma-sdk/test": ^1.52.4
  "@platforma-sdk/tengo-builder": ^2.4.11
  "@platforma-sdk/package-builder": ^3.11.0
  "@platforma-sdk/eslint-config": ^1.2.0


  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-254-develop
  '@platforma-open/milaboratories.software-repseqio': ^2.5.0-13-master

  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid

  '@milaboratories/helpers': ^1.13.0
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  '@vueuse/core': ^13.5.0
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.4

  "vite": ^6.2.2
  "vitest": ^4.0.17
  '@zip.js/zip.js': ^2.8.2
  '@types/wicg-file-system-access': ^2023.10.6
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.29.4
  "@platforma-sdk/blocks-deps-updater": ^2.0.0
