packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.3
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.8.0
  '@platforma-sdk/model': 1.52.3
  '@platforma-sdk/ui-vue': 1.52.3
  '@platforma-sdk/tengo-builder': 2.4.11
  '@platforma-sdk/package-builder': 3.11.0
  '@platforma-sdk/block-tools': 2.6.31
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.52.4
  '@milaboratories/helpers': 1.12.1

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.24
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.17
  'eslint': ^9.25.1
  '@changesets/cli': ^2.29.8

  # Block-specific dependencies
  '@platforma-open/milaboratories.runenv-python-3': 1.1.16
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-279-develop
  '@platforma-open/milaboratories.software-repseqio': ^2.5.0-13-master
  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid
  '@vueuse/core': ^13.5.0
  '@zip.js/zip.js': ^2.8.2
  '@types/wicg-file-system-access': ^2023.10.6
  'zod': ^3.23.8
