packages:
  - model
  - ui
  - workflow
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.43.0
  "@platforma-sdk/ui-vue": ^1.43.1
  "@platforma-sdk/workflow-tengo": ^5.2.0
  "@platforma-sdk/block-tools": ^2.6.3
  "@platforma-sdk/test": ^1.43.0
  "@platforma-sdk/tengo-builder": ^2.1.19
  "@platforma-sdk/package-builder": ^2.16.1
  "@platforma-sdk/eslint-config": ^1.0.3


  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-169-develop
  '@platforma-open/milaboratories.software-repseqio': ^2.5.0-13-master

  'ag-grid-enterprise': &ag-grid ^34.1.1
  'ag-grid-vue3': *ag-grid

  '@milaboratories/helpers': ^1.8.0
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  '@vueuse/core': ^13.5.0
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.4

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.29.4
  "js-yaml": "^4.1.0"
